#!/usr/bin/env python
# -*- encoding: utf-8 -*-
"""
Concourse in resource
"""
# Python 2 and 3 compatibility
from __future__ import unicode_literals

import sys
from resource import Resource


if __name__ == '__main__':
    r = Resource()
    try:
        rcode = r.run(os.path.basename(__file__))
    except Exception as e:
        sys.stderr.write("ERROR: " + str(e) + "\n")
        sys.exit(1)
    sys.exit(rcode)

